### ISSUE TITLE
Linux Support

### ISSUE THREAD

**Issue by riley-spires** [JeLuF/mountain-displaypad#3]
I have been able to get this to work on linux (Fedora 41)for the most part

I have been able to do this by changing
```javascript
let displayPath = connectedDisplaypads.filter((device) => {
return device.interface==1
})[0].path
```
to
```javascript
let displayPath = connectedDisplaypads.filter((device) => {
return device.interface==0
})[0].path
```

However, I cannot change any of the displays because it fails to write to the rawhid. Below are my available devices by Mountain in a table
```console
┌─────────┬──────────┬───────────┬────────────────┬──────────────┬──────────────┬───────────────────────┬─────────┬───────────┬───────────┬───────┐
│ (index) │ vendorId │ productId │ path           │ serialNumber │ manufacturer │ product               │ release │ interface │ usagePage │ usage │
├─────────┼──────────┼───────────┼────────────────┼──────────────┼──────────────┼───────────────────────┼─────────┼───────────┼───────────┼───────┤
│ 0       │ 12930    │ 9         │ '/dev/hidraw0' │ ''           │ 'Mountain'   │ 'MOUNTAIN DisplayPad' │ 7       │ 0         │ 1         │ 6     │
│ 1       │ 12930    │ 9         │ '/dev/hidraw0' │ ''           │ 'Mountain'   │ 'MOUNTAIN DisplayPad' │ 7       │ 0         │ 12        │ 1     │
│ 2       │ 12930    │ 9         │ '/dev/hidraw0' │ ''           │ 'Mountain'   │ 'MOUNTAIN DisplayPad' │ 7       │ 0         │ 1         │ 128   │
│ 3       │ 12930    │ 9         │ '/dev/hidraw0' │ ''           │ 'Mountain'   │ 'MOUNTAIN DisplayPad' │ 7       │ 0         │ 1         │ 2     │
│ 4       │ 12930    │ 9         │ '/dev/hidraw0' │ ''           │ 'Mountain'   │ 'MOUNTAIN DisplayPad' │ 7       │ 0         │ 1         │ 1     │
│ 5       │ 12930    │ 9         │ '/dev/hidraw1' │ ''           │ 'Mountain'   │ 'MOUNTAIN DisplayPad' │ 7       │ 3         │ 65280     │ 1     │
└─────────┴──────────┴───────────┴────────────────┴──────────────┴──────────────┴───────────────────────┴─────────┴───────────┴───────────┴───────┘
```

And below here is a stack trace of the error whenever I try to use `pad.fillColor(0, 255, 0, 0)`

 ```console
 node:events:496
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot write to hid device
    at Displaypad._processDataEvent (/mnt/MassStorage/CodeLibrary/JavaScript/mountain-test/node_modules/mountain-displaypad/index.js:283:26)
    at HID.<anonymous> (/mnt/MassStorage/CodeLibrary/JavaScript/mountain-test/node_modules/mountain-displaypad/index.js:137:9)
    at HID.emit (node:events:518:28)
    at readFunc (/mnt/MassStorage/CodeLibrary/JavaScript/mountain-test/node_modules/node-hid/nodehid.js:117:26)
Emitted 'error' event on Displaypad instance at:
    at HID.<anonymous> (/mnt/MassStorage/CodeLibrary/JavaScript/mountain-test/node_modules/mountain-displaypad/index.js:141:9)
    at HID.emit (node:events:518:28)
    at Immediate.<anonymous> (/mnt/MassStorage/CodeLibrary/JavaScript/mountain-test/node_modules/node-hid/nodehid.js:122:26)
    at process.processImmediate (node:internal/timers:491:21)

Node.js v22.11.0
```

I will be more than willing to test possible solutions or brainstorm with others. This is the only way I've gotten this specific device to work on linux so far.

**Comment by riley-spires** [comment]
Just a note for the first part of this issue, I have no HID devices from Mountain with interface 1. I have 5 devices showing from node-hid with interface 0 and 1 device showing with interface 3.

**Comment by JeLuF** [comment]
Do you have write permissions for /dev/hidraw*?

**Comment by not-coded** [comment]
I am having the same stacktrace even when running it with root privileges. But I had to do some extra steps.

1. When I apply riley-spires' changes (setting displayPath's `device.interface` to 0), it sends the data to initialize the device but the screen never lights up with the Mountain Logo and it doesn't respond to the init message either.

2. However when I change devicePath's `device.interface` to 0 (setting both paths' interfaces to 0), the screen does light up with the Mountain Logo as normally, but still doesn't respond to the init message. 

3. Interestingly, changing devicePath's `device.interface` to 0 and displayPath's `device.interface` to 3, the Mountain Logo appears as the first key (the one that leads you to the website to install the Mountain Base Camp app), pressing it sends the same keystrokes as on Windows.

https://github.com/user-attachments/assets/4c431ac4-7dc4-401a-9540-a5e9412b7e30


The workaround around this is changing the devicePath's `device.interface` to 0 (setting both paths' interfaces to 0) to get to the lit up screen without init message, then changing the devicePath's `device.interface` back to 3 and running it without disconnecting the device (still with screen lit up but no init message) finally "works" and responds to the init message, then errors out to the same stacktrace message as riley-spires'.


https://github.com/user-attachments/assets/d273a21c-1d4f-47bd-84fd-950d9fafc670

```
node:events:496
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot write to hid device
    at Displaypad._processDataEvent (/mnt/Dev Drive/Source Codes/mountain-displaypad-gui/node_modules/mountain-displaypad/index.js:287:26)
    at HID.<anonymous> (/mnt/Dev Drive/Source Codes/mountain-displaypad-gui/node_modules/mountain-displaypad/index.js:139:9)
    at HID.emit (node:events:518:28)
    at readFunc (/mnt/Dev Drive/Source Codes/mountain-displaypad-gui/node_modules/node-hid/nodehid.js:117:26)
Emitted 'error' event on Displaypad instance at:
    at HID.<anonymous> (/mnt/Dev Drive/Source Codes/mountain-displaypad-gui/node_modules/mountain-displaypad/index.js:143:9)
    at HID.emit (node:events:518:28)
    at Immediate.<anonymous> (/mnt/Dev Drive/Source Codes/mountain-displaypad-gui/node_modules/node-hid/nodehid.js:122:26)
    at process.processImmediate (node:internal/timers:483:21)

Node.js v20.18.2
```

Here's info about my DisplayPad:
vendorId | productId | path | serialNumber | manufacturer | product | release | interface | usagePage | usage
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
12930 | 9 | /dev/hidraw12 |   | Mountain | MOUNTAIN DisplayPad | 4 | 0 | 1 | 6
12930 | 9 | /dev/hidraw12 |   | Mountain | MOUNTAIN DisplayPad | 4 | 0 | 12 | 1
12930 | 9 | /dev/hidraw12 |   | Mountain | MOUNTAIN DisplayPad | 4 | 0 | 1 | 128
12930 | 9 | /dev/hidraw12 |   | Mountain | MOUNTAIN DisplayPad | 4 | 0 | 1 | 2
12930 | 9 | /dev/hidraw12 |   | Mountain | MOUNTAIN DisplayPad | 4 | 0 | 1 | 1
12930 | 9 | /dev/hidraw13 |   | Mountain | MOUNTAIN DisplayPad | 4 | 3 | 65280 | 1


If you need any more information or need testing, let me know! I hope you understand what I wrote and possibly fix this.
